//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Subject
    {
        public int SubID { get; set; }

        [Required(ErrorMessage = "Subject Name is Required")]
        [StringLength(50, ErrorMessage = "Subject Name cannot exceed 50 characters.")]
        public string SubjectName { get; set; }
        public int StandardID { get; set; }
    
        public virtual Standard Standard { get; set; }
    }
}
